/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProductosSlugRouteImport } from './routes/productos.$slug'
import { Route as RecetarioIndexRouteImport } from './routes/recetario.index'
import { Route as RecetarioSlugRouteImport } from './routes/recetario.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosSlugRoute = ProductosSlugRouteImport.update({
  id: '/productos/$slug',
  path: '/productos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetarioIndexRoute = RecetarioIndexRouteImport.update({
  id: '/recetario/',
  path: '/recetario/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecetarioSlugRoute = RecetarioSlugRouteImport.update({
  id: '/recetario/$slug',
  path: '/recetario/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/recetario/$slug': typeof RecetarioSlugRoute
  '/recetario/': typeof RecetarioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/recetario/$slug': typeof RecetarioSlugRoute
  '/recetario': typeof RecetarioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/productos/$slug': typeof ProductosSlugRoute
  '/recetario/$slug': typeof RecetarioSlugRoute
  '/recetario/': typeof RecetarioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/productos/$slug'
    | '/recetario/$slug'
    | '/recetario/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/productos/$slug'
    | '/recetario/$slug'
    | '/recetario'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/productos/$slug'
    | '/recetario/$slug'
    | '/recetario/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductosSlugRoute: typeof ProductosSlugRoute
  RecetarioSlugRoute: typeof RecetarioSlugRoute
  RecetarioIndexRoute: typeof RecetarioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos/$slug': {
      id: '/productos/$slug'
      path: '/productos/$slug'
      fullPath: '/productos/$slug'
      preLoaderRoute: typeof ProductosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetario/': {
      id: '/recetario/'
      path: '/recetario'
      fullPath: '/recetario/'
      preLoaderRoute: typeof RecetarioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recetario/$slug': {
      id: '/recetario/$slug'
      path: '/recetario/$slug'
      fullPath: '/recetario/$slug'
      preLoaderRoute: typeof RecetarioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductosSlugRoute: ProductosSlugRoute,
  RecetarioSlugRoute: RecetarioSlugRoute,
  RecetarioIndexRoute: RecetarioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
